import 'package:flutter/foundation.dart';
import 'package:shared_preferences/shared_preferences.dart';
import '../constants/app_strings.dart';

class LanguageProvider extends ChangeNotifier {
  static const _storageKey = 'anxietycare_language';
  static const _supportedCodes = {'en', 'so'};
  static const _translations = {
    'en': {
      'language': 'Language',
      'english': 'English',
      'somali': 'Somali',
      'settings': 'Settings',
      'appearance': 'Appearance',
      'chooseAppearance': 'Choose how AnxietyCare looks on this device.',
      'lightMode': 'Light Mode',
      'darkMode': 'Dark Mode',
      'systemDefault': 'System Default',
      'account': 'Account',
      'profile': 'Profile',
      'notifications': 'Notifications',
      'healthHistory': 'Health history',
      'privacySecurity': 'Privacy & Security',
      'password': 'Password',
      'privacy': 'Privacy',
      'helpSupport': 'Help & Support',
      'aboutApplication': 'About Application',
      'logout': 'Logout',
      'clearSession': 'Clear secure session and return to login',
      'welcomeToAnxietyCare': 'Welcome to AnxietyCare',
      'loginSubtitle': 'Private mental health support, assessments, doctors, bookings, and updates in one calm space.',
      'signInSecurely': 'Sign in securely',
      'patientAccountsOnly': 'Patient accounts only on mobile.',
      'username': 'Username',
      'enterUsername': 'Enter your username',
      'enterPassword': 'Enter your password',
      'usernameRequired': 'Username is required.',
      'passwordRequired': 'Password is required.',
      'forgotPassword': 'Forgot Password?',
      'login': 'Login',
      'dontHaveAccount': "Don't have an account?",
      'signUp': 'Sign Up',
      'loginSuccess': 'Login successful',
      'assessment': 'Assessment',
      'continue': 'Continue',
      'analyze': 'Analyze',
      'backToMood': 'Back to mood selection',
      'minimumAssessmentText': 'Please enter at least 20 meaningful characters.',
      'register': 'Register',
      'confirmPassword': 'Confirm Password',
      'fullName': 'Full Name',
      'phone': 'Phone Number',
      'gender': 'Gender',
      'dateOfBirth': 'Date of Birth',
      'age': 'Age',
      'male': 'Male',
      'female': 'Female',
      'alreadyHaveAccount': 'Already have an account?',
      'enterDetails': 'Enter your details to continue',
      'createAccount': 'Create your account',
      'requiredField': 'This field is required',
      'invalidPhone': 'Enter a valid phone number',
      'passwordTooShort': 'Password must be at least 8 characters',
      'passwordRequirements': 'Use at least 8 characters with uppercase, lowercase, number, and symbol',
      'passwordMismatch': 'Passwords do not match',
      'invalidUsername': 'Username must be at least 3 characters',
      'invalidAge': 'Enter a valid age',
      'dashboard': 'Dashboard',
      'welcome': 'Welcome',
      'mentalHealthScore': 'Mental Health Score',
      'latestPrediction': 'Latest Prediction',
      'upcomingAppointment': 'Upcoming Appointment',
      'assessmentCount': 'Assessments Taken',
      'takeAssessment': 'Take Assessment',
      'bookDoctor': 'Book Doctor',
      'predictionHistory': 'Prediction History',
      'home': 'Home',
      'bookings': 'Bookings',
      'assessmentQuestion': 'How have you been feeling today and during the past few days?',
      'assessmentDescription': 'Share your thoughts and feelings for our AI analysis',
      'analyzing': 'Analyzing...',
      'enterAtLeast10Chars': 'Please enter at least 10 characters',
      'neutral': 'Neutral',
      'anxiety': 'Anxiety',
      'depression': 'Depression',
      'predictionResult': 'Prediction Result',
      'yourHealthCondition': 'Your Health Condition',
      'yourHealthRequiresAttention': 'Your health condition requires attention.',
      'mentalWellnessRecommendations': 'Mental wellness recommendations',
      'mentorSupport': 'Mentor support available',
      'recommendations': 'Recommendations',
      'mentalWellnessTips': 'Mental Wellness Tips',
      'sleepTips': 'Sleep Tips',
      'exerciseAdvice': 'Exercise Advice',
      'stressReductionTips': 'Stress Reduction Tips',
      'doctors': 'Available Doctors',
      'doctorProfile': 'Doctor Profile',
      'doctorName': 'Doctor Name',
      'rating': 'Rating',
      'specialization': 'Specialization',
      'hospital': 'Hospital',
      'fee': 'Consultation Fee',
      'experience': 'Experience',
      'biography': 'Biography',
      'availableDays': 'Available Days',
      'availableTimeSlots': 'Available Time Slots',
      'bookAppointment': 'Book Appointment',
      'searchDoctors': 'Search doctors...',
      'booking': 'Booking',
      'selectedDoctor': 'Selected Doctor',
      'selectedDate': 'Selected Date',
      'selectedTime': 'Selected Time',
      'notes': 'Notes',
      'confirmBooking': 'Confirm Booking',
      'selectDate': 'Select Date',
      'selectTime': 'Select Time',
      'payment': 'Payment',
      'paymentMethod': 'Payment Method',
      'phoneNumber': 'Phone Number',
      'amount': 'Amount',
      'description': 'Description',
      'payNow': 'Pay Now',
      'paymentProcessing': 'Processing payment...',
      'success': 'Success',
      'appointmentConfirmed': 'Appointment Confirmed',
      'bookingConfirmation': 'Booking Confirmation',
      'appointmentConfirmedDesc': 'Your appointment has been confirmed',
      'referenceNumber': 'Reference Number',
      'returnHome': 'Return Home',
      'appointmentReminder': 'Appointment Reminder',
      'paymentConfirmation': 'Payment Confirmation',
      'markAsRead': 'Mark as read',
      'clearAll': 'Clear all',
      'noNotifications': 'No notifications',
      'editProfile': 'Edit Profile',
      'appointmentHistory': 'Appointment History',
      'changePassword': 'Change Password',
      'logoutConfirm': 'Are you sure you want to logout?',
      'upcoming': 'Upcoming',
      'completed': 'Completed',
      'cancelled': 'Cancelled',
      'noUpcomingAppointments': 'No upcoming appointments',
      'noCompletedAppointments': 'No completed appointments',
      'noCancelledAppointments': 'No cancelled appointments',
      'error': 'Error',
      'errorOccurred': 'An error occurred',
      'tryAgain': 'Try Again',
      'noInternet': 'No internet connection',
      'serverError': 'Server error. Please try again later',
      'invalidCredentials': 'Invalid username or password',
      'userAlreadyExists': 'Username already exists',
      'registerSuccess': 'Account created successfully',
      'passwordChanged': 'Password changed successfully',
      'profileUpdated': 'Profile updated successfully',
      'loading': 'Loading...',
      'pleaseWait': 'Please wait...',
    },
    'so': {
      'language': 'Luqad',
      'english': 'Ingiriisi',
      'somali': 'Soomaali',
      'settings': 'Dejinta',
      'appearance': 'Muuqaalka',
      'chooseAppearance': 'Dooro sida AnxietyCare uga muuqaneyso qalabkan.',
      'lightMode': 'Hab Iftiin',
      'darkMode': 'Hab Madow',
      'systemDefault': 'Raac nidaamka taleefanka',
      'account': 'Akoon',
      'profile': 'Akoon',
      'notifications': 'Ogeysiisyo',
      'healthHistory': 'Taariikhda caafimaadka',
      'privacySecurity': 'Asturnaanta & Amniga',
      'password': 'Furaha sirta',
      'privacy': 'Asturnaan',
      'helpSupport': 'Caawimo & Taageero',
      'aboutApplication': 'Ku saabsan app-ka',
      'logout': 'Ka bax',
      'clearSession': 'Nadiifi fadhiga amniga oo ku noqo gelitaanka',
      'welcomeToAnxietyCare': 'Ku soo dhawoow AnxietyCare',
      'loginSubtitle': 'Taageero caafimaad maskaxeed, qiimeyn, dhakhaatiir, ballamo, iyo ogeysiisyo meel deggan ku wada jira.',
      'signInSecurely': 'Si ammaan ah u gal',
      'patientAccountsOnly': 'Akoonnada bukaanka waxay ku shaqeeyaan mobile-ka oo keliya.',
      'username': 'Magaca isticmaalaha',
      'enterUsername': 'Geli magaca isticmaalaha',
      'enterPassword': 'Geli furaha sirta',
      'usernameRequired': 'Magaca isticmaalaha waa qasab.',
      'passwordRequired': 'Furaha sirta waa qasab.',
      'forgotPassword': 'Ma illowday furaha?',
      'login': 'Gal',
      'dontHaveAccount': 'Akoon ma lihid?',
      'signUp': 'Is diiwaangeli',
      'loginSuccess': 'Gelitaanka waa lagu guuleystay',
      'assessment': 'Qiimeyn',
      'continue': 'Sii wad',
      'analyze': 'Falanqee',
      'backToMood': 'Ku noqo doorashada niyadda',
      'minimumAssessmentText': 'Fadlan geli ugu yaraan 20 xaraf oo macno leh.',
      'register': 'Is diiwaangeli',
      'confirmPassword': 'Xaqiiji furaha sirta',
      'fullName': 'Magac buuxa',
      'phone': 'Lambarka telefoonka',
      'gender': 'Jinsi',
      'dateOfBirth': 'Taariikhda dhalashada',
      'age': 'Da',
      'male': 'Lab',
      'female': 'Dhedig',
      'alreadyHaveAccount': 'Akoon hore ma leedahay?',
      'enterDetails': 'Geli faahfaahintaada si aad u sii wadato',
      'createAccount': 'Abuur akoonkaaga',
      'requiredField': 'Goobtan waa qasab',
      'invalidPhone': 'Geli lambar telefoon sax ah',
      'passwordTooShort': 'Furaha sirta waa inuu ahaadaa ugu yaraan 8 xaraf',
      'passwordRequirements': 'Isticmaal ugu yaraan 8 xaraf oo leh xaraf weyn, xaraf yar, lambar, iyo calaamad',
      'passwordMismatch': 'Furayaasha sirta isma waafaqaan',
      'invalidUsername': 'Magaca isticmaalaha waa inuu ahaadaa ugu yaraan 3 xaraf',
      'invalidAge': 'Geli da sax ah',
      'dashboard': 'Dashboard',
      'welcome': 'Soo dhawoow',
      'mentalHealthScore': 'Dhibcaha Caafimaadka Maskaxda',
      'latestPrediction': 'Saadaashii U Dambeysay',
      'upcomingAppointment': 'Ballanta Soo Socota',
      'assessmentCount': 'Qiimeynno La Qaaday',
      'takeAssessment': 'Qaado Qiimeyn',
      'bookDoctor': 'Ballan Dhakhtar',
      'predictionHistory': 'Taariikhda Saadaasha',
      'home': 'Hoy',
      'bookings': 'Ballamo',
      'assessmentQuestion': 'Sidee ayaad dareemaysay maanta iyo maalmahan dhow?',
      'assessmentDescription': 'La wadaag fikirkaaga iyo dareenkaaga falanqeynta AI',
      'analyzing': 'Waa la falanqeynayaa...',
      'enterAtLeast10Chars': 'Fadlan geli ugu yaraan 10 xaraf',
      'neutral': 'Caadi',
      'anxiety': 'Welwel',
      'depression': 'Niyad-jab',
      'predictionResult': 'Natiijada Saadaasha',
      'yourHealthCondition': 'Xaaladdaada Caafimaad',
      'yourHealthRequiresAttention': 'Xaaladdaada caafimaad waxay u baahan tahay fiiro gaar ah.',
      'mentalWellnessRecommendations': 'Talooyin caafimaadka maskaxda',
      'mentorSupport': 'Taageero la-taliye ayaa jirta',
      'recommendations': 'Talooyin',
      'mentalWellnessTips': 'Talooyin Caafimaad Maskaxeed',
      'sleepTips': 'Talooyin Hurdo',
      'exerciseAdvice': 'Talo Jimicsi',
      'stressReductionTips': 'Talooyin Yareynta Cadaadiska',
      'doctors': 'Dhakhaatiirta La Heli Karo',
      'doctorProfile': 'Akoonka Dhakhtarka',
      'doctorName': 'Magaca Dhakhtarka',
      'rating': 'Qiimeyn',
      'specialization': 'Takhasus',
      'hospital': 'Isbitaal',
      'fee': 'Lacagta La-tashiga',
      'experience': 'Khibrad',
      'biography': 'Taariikh Nololeed',
      'availableDays': 'Maalmaha La Heli Karo',
      'availableTimeSlots': 'Waqtiyada La Heli Karo',
      'bookAppointment': 'Qabso Ballan',
      'searchDoctors': 'Raadi dhakhaatiir...',
      'booking': 'Ballan',
      'selectedDoctor': 'Dhakhtarka La Doortay',
      'selectedDate': 'Taariikhda La Doortay',
      'selectedTime': 'Waqtiga La Doortay',
      'notes': 'Qoraallo',
      'confirmBooking': 'Xaqiiji Ballanta',
      'selectDate': 'Dooro Taariikh',
      'selectTime': 'Dooro Waqti',
      'payment': 'Lacag Bixin',
      'paymentMethod': 'Habka Lacag Bixinta',
      'phoneNumber': 'Lambarka Telefoonka',
      'amount': 'Qaddar',
      'description': 'Sharaxaad',
      'payNow': 'Bixi Hadda',
      'paymentProcessing': 'Lacag bixinta waa socotaa...',
      'success': 'Guul',
      'appointmentConfirmed': 'Ballanta Waa La Xaqiijiyay',
      'bookingConfirmation': 'Xaqiijinta Ballanta',
      'appointmentConfirmedDesc': 'Ballantaada waa la xaqiijiyay',
      'referenceNumber': 'Lambarka Tixraaca',
      'returnHome': 'Ku Noqo Hoyga',
      'appointmentReminder': 'Xusuusin Ballan',
      'paymentConfirmation': 'Xaqiijinta Lacag Bixinta',
      'markAsRead': 'Calaamadee in la akhriyay',
      'clearAll': 'Nadiifi dhammaan',
      'noNotifications': 'Ogeysiisyo ma jiraan',
      'editProfile': 'Wax ka beddel Akoonka',
      'appointmentHistory': 'Taariikhda Ballamaha',
      'changePassword': 'Beddel Furaha Sirta',
      'logoutConfirm': 'Ma hubtaa inaad ka baxayso?',
      'upcoming': 'Soo socda',
      'completed': 'Dhammeystiran',
      'cancelled': 'La joojiyay',
      'noUpcomingAppointments': 'Ballamo soo socda ma jiraan',
      'noCompletedAppointments': 'Ballamo dhammeystiran ma jiraan',
      'noCancelledAppointments': 'Ballamo la joojiyay ma jiraan',
      'error': 'Khalad',
      'errorOccurred': 'Khalad ayaa dhacay',
      'tryAgain': 'Isku day mar kale',
      'noInternet': 'Internet ma jiro',
      'serverError': 'Khalad server. Fadlan mar kale isku day',
      'invalidCredentials': 'Magaca isticmaalaha ama furaha sirta waa khalad',
      'userAlreadyExists': 'Magaca isticmaalaha hore ayuu u jiray',
      'registerSuccess': 'Akoonka si guul leh ayaa loo abuuray',
      'passwordChanged': 'Furaha sirta si guul leh ayaa loo beddelay',
      'profileUpdated': 'Akoonka si guul leh ayaa loo cusbooneysiiyay',
      'loading': 'Waa la rarayaa...',
      'pleaseWait': 'Fadlan sug...',
    },
  };
  String _languageCode = 'en';

  String get languageCode => _languageCode;
  bool get isSomali => _languageCode == 'so';

  Future<void> loadLanguage() async {
    final prefs = await SharedPreferences.getInstance();
    final stored = prefs.getString(_storageKey);
    if (stored != null && _supportedCodes.contains(stored)) {
      _languageCode = stored;
    }
    AppStrings.setLanguage(_languageCode);
    notifyListeners();
  }

  Future<void> setLanguage(String languageCode) async {
    if (!_supportedCodes.contains(languageCode)) return;
    _languageCode = languageCode;
    AppStrings.setLanguage(_languageCode);
    final prefs = await SharedPreferences.getInstance();
    await prefs.setString(_storageKey, languageCode);
    notifyListeners();
  }

  String translate(String key) {
    return _translations[_languageCode]?[key] ??
        _translations['en']?[key] ??
        key;
  }
}
